---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hao.
--- DateTime: 2022/4/23 10:36
---
--1.参数列表
--1.1优惠券id
local voucherId = ARGV[1]
--1.2用户id
local userId = ARGV[2];
--1.3订单id
local orderId = ARGV[3];
--2.数据key
--2.1库存key
local stockKey = 'seckill:stock:'..voucherId..':'
--2.2 订单key
local orderKey = 'seckill:order:'..voucherId..':'

--3.判断库存是否充足

if (tonumber(redis.call('get', stockKey)) <= 0) then
    --3.1库存不足，返回1
    return 1;
end



--4.判断用户是否重复下单
if (redis.call('SISMEMBER', orderKey,userId) == 1) then
    --4.1存在，说明是重复下单返回2
    return 2
end

--5.扣减库存
redis.call('incrby',stockKey,-1)
--6.把用户id存入
redis.call('sadd',orderKey,userId)
--7.发送消息到消息队列
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0