---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hao.
--- DateTime: 2022/4/22 16:08
---
--获取锁中的线程标示 get key
local id = redis.call('get',KEYS[1])

--比较线程标示与锁中的标示是否一致
if(id == ARGV[1]) then
    -- 释放锁del key
    return redis.call('del',KEYS[1])
end
return 0;